/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassRegistrationPageRouteImport } from './routes/class-registration-page'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExamInformationRouteImport } from './routes/exam-information'
import { Route as MeetYourInstructorsRouteImport } from './routes/meet-your-instructors'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminInstructorsRouteImport } from './routes/admin.instructors'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as EventsLocationRouteImport } from './routes/events.location'
import { Route as AdminPagesIndexRouteImport } from './routes/admin.pages.index'
import { Route as AdminPagesSlugRouteImport } from './routes/admin.pages.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassRegistrationPageRoute = ClassRegistrationPageRouteImport.update({
  id: '/class-registration-page',
  path: '/class-registration-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamInformationRoute = ExamInformationRouteImport.update({
  id: '/exam-information',
  path: '/exam-information',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetYourInstructorsRoute = MeetYourInstructorsRouteImport.update({
  id: '/meet-your-instructors',
  path: '/meet-your-instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstructorsRoute = AdminInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const EventsLocationRoute = EventsLocationRouteImport.update({
  id: '/events/location',
  path: '/events/location',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesSlugRoute = AdminPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/class-registration-page': typeof ClassRegistrationPageRoute
  '/contact-us': typeof ContactUsRoute
  '/dashboard': typeof DashboardRoute
  '/exam-information': typeof ExamInformationRoute
  '/meet-your-instructors': typeof MeetYourInstructorsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/events/location': typeof EventsLocationRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/auth': typeof AuthRoute
  '/class-registration-page': typeof ClassRegistrationPageRoute
  '/contact-us': typeof ContactUsRoute
  '/dashboard': typeof DashboardRoute
  '/exam-information': typeof ExamInformationRoute
  '/meet-your-instructors': typeof MeetYourInstructorsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/events/location': typeof EventsLocationRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/pages': typeof AdminPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/class-registration-page': typeof ClassRegistrationPageRoute
  '/contact-us': typeof ContactUsRoute
  '/dashboard': typeof DashboardRoute
  '/exam-information': typeof ExamInformationRoute
  '/meet-your-instructors': typeof MeetYourInstructorsRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/instructors': typeof AdminInstructorsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/events/location': typeof EventsLocationRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/auth'
    | '/class-registration-page'
    | '/contact-us'
    | '/dashboard'
    | '/exam-information'
    | '/meet-your-instructors'
    | '/admin/classes'
    | '/admin/instructors'
    | '/admin/resources'
    | '/admin/settings'
    | '/events/location'
    | '/admin/'
    | '/admin/pages/$slug'
    | '/admin/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/auth'
    | '/class-registration-page'
    | '/contact-us'
    | '/dashboard'
    | '/exam-information'
    | '/meet-your-instructors'
    | '/admin/classes'
    | '/admin/instructors'
    | '/admin/resources'
    | '/admin/settings'
    | '/events/location'
    | '/admin'
    | '/admin/pages/$slug'
    | '/admin/pages'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/auth'
    | '/class-registration-page'
    | '/contact-us'
    | '/dashboard'
    | '/exam-information'
    | '/meet-your-instructors'
    | '/admin/classes'
    | '/admin/instructors'
    | '/admin/resources'
    | '/admin/settings'
    | '/events/location'
    | '/admin/'
    | '/admin/pages/$slug'
    | '/admin/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClassRegistrationPageRoute: typeof ClassRegistrationPageRoute
  ContactUsRoute: typeof ContactUsRoute
  DashboardRoute: typeof DashboardRoute
  ExamInformationRoute: typeof ExamInformationRoute
  MeetYourInstructorsRoute: typeof MeetYourInstructorsRoute
  EventsLocationRoute: typeof EventsLocationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class-registration-page': {
      id: '/class-registration-page'
      path: '/class-registration-page'
      fullPath: '/class-registration-page'
      preLoaderRoute: typeof ClassRegistrationPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-information': {
      id: '/exam-information'
      path: '/exam-information'
      fullPath: '/exam-information'
      preLoaderRoute: typeof ExamInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-your-instructors': {
      id: '/meet-your-instructors'
      path: '/meet-your-instructors'
      fullPath: '/meet-your-instructors'
      preLoaderRoute: typeof MeetYourInstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructors': {
      id: '/admin/instructors'
      path: '/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof AdminInstructorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/location': {
      id: '/events/location'
      path: '/events/location'
      fullPath: '/events/location'
      preLoaderRoute: typeof EventsLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/$slug': {
      id: '/admin/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/admin/pages/$slug'
      preLoaderRoute: typeof AdminPagesSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClassesRoute: typeof AdminClassesRoute
  AdminInstructorsRoute: typeof AdminInstructorsRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPagesSlugRoute: typeof AdminPagesSlugRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClassesRoute: AdminClassesRoute,
  AdminInstructorsRoute: AdminInstructorsRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPagesSlugRoute: AdminPagesSlugRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ClassRegistrationPageRoute: ClassRegistrationPageRoute,
  ContactUsRoute: ContactUsRoute,
  DashboardRoute: DashboardRoute,
  ExamInformationRoute: ExamInformationRoute,
  MeetYourInstructorsRoute: MeetYourInstructorsRoute,
  EventsLocationRoute: EventsLocationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
